### ISSUE TITLE
Mission Imprintables

### ISSUE THREAD

**Issue by ll1898** [ll1898/Breaches#1]
Fast fashion company website breach, exposed all person information of customers

**Comment by ll1898** [comment]
toobig

**Comment by ll1898** [comment]
f

**Comment by ch8540** [comment]
Info:
Date Posted - May 2021
Date Downloaded - May 2021
 
Account - /
Source Location - daserv/ll1898

Company Description - Online clothing store
Compromised Info -

Config:
ID - missionimprintables
Name - Mission Imprintables
Host - Conti
Actor - Conti
Associations -
URL - http://continewsnv5otx5kaoje7krkto2qbu3gtqef22mnr7eaxw3y6ncz3ad.onion/c

Files Indexed:
Dev -
Prod -

Notes:
Date | 6-June redownload
